In [9]:
import numpy as np
import pandas as pd
import random
input_nodes = 9
hidden_nodes = 4
output_nodes = 6
wei_inp_hid = np.random.randint(-10, 10, (hidden_nodes, input_nodes))
wei_inp_hid

array([[-9,  6,  1, -5,  4,  9,  4,  8, -3],
       [ 9,  3, -8, -7,  6, -2, -3,  4, -7],
       [-9,  8,  6,  5, -3, -3, -3,  4, -3],
       [-5, -7, -2,  7, -5, -1,  1,  9, -5]])

In [10]:
active_input_percentage = 0.6
active_input_nodes = int(input_nodes * active_input_percentage)
active_input_indices = sorted(random.sample(range(0, input_nodes), 
                              active_input_nodes))
active_input_indices

[1, 5, 6, 7, 8]

In [11]:
wei_inp_hid_old = wei_inp_hid.copy()
wei_inp_hid = wei_inp_hid[:, active_input_indices]
wei_inp_hid

array([[ 6,  9,  4,  8, -3],
       [ 3, -2, -3,  4, -7],
       [ 8, -3, -3,  4, -3],
       [-7, -1,  1,  9, -5]])

In [12]:
wei_hid_out = np.random.randint(-10, 10, (output_nodes, hidden_nodes))
print(wei_hid_out)
active_hidden_percentage = 0.7
active_hidden_nodes = int(hidden_nodes * active_hidden_percentage)
active_hidden_indices = sorted(random.sample(range(0, hidden_nodes), 
                             active_hidden_nodes))
print(active_hidden_indices)
wei_hid_out_old = wei_hid_out.copy()
wei_hid_out = wei_hid_out[:, active_hidden_indices]
print(wei_hid_out)

[[ 9 -1 -2 -3]
 [-7 -2  6  7]
 [ 2 -6  9 -6]
 [-5  0  5 -9]
 [ 8  9  0  3]
 [ 5  8 -3  9]]
[0, 2]
[[ 9 -2]
 [-7  6]
 [ 2  9]
 [-5  5]
 [ 8  0]
 [ 5 -3]]


In [13]:
wei_inp_hid = wei_inp_hid[active_hidden_indices]
wei_inp_hid

array([[ 6,  9,  4,  8, -3],
       [ 8, -3, -3,  4, -3]])

In [14]:
import numpy as np
import random
input_nodes = 10
hidden_nodes = 5
output_nodes = 7
wei_inp_hid = np.random.randint(-10, 10, (hidden_nodes, input_nodes))
print("wei_inp_hid: \n", wei_inp_hid)
wei_hid_out = np.random.randint(-10, 10, (output_nodes, hidden_nodes))
print("wei_hid_out:\n", wei_hid_out)
active_input_percentage = 0.7
active_hidden_percentage = 0.7
active_input_nodes = int(input_nodes * active_input_percentage)
active_input_indices = sorted(random.sample(range(0, input_nodes), 
                              active_input_nodes))
print("\nactive input indices: ", active_input_indices)
active_hidden_nodes = int(hidden_nodes * active_hidden_percentage)
active_hidden_indices = sorted(random.sample(range(0, hidden_nodes), 
                             active_hidden_nodes))
print("active hidden indices: ", active_hidden_indices)
wei_inp_hid_old = wei_inp_hid.copy()
wei_inp_hid = wei_inp_hid[:, active_input_indices]
print("\nweight_input_hidden after deactivating input nodes:\n", wei_inp_hid)
wei_inp_hid = wei_inp_hid[active_hidden_indices]
print("\nweight_input_hidden after deactivating hidden nodes:\n", wei_inp_hid)
wei_hid_out_old = wei_hid_out.copy()
wei_hid_out = wei_hid_out[:, active_hidden_indices]
print("\nweight_output_hidden after deactivating hidden nodes:\n", wei_hid_out)

wei_inp_hid: 
 [[  1   1   6  -3  -3   1   0  -8   9   3]
 [ -2  -5 -10   4  -4   1   3   9  -8   2]
 [  8   6   4   3   4  -2   8   5   7   5]
 [  4   2 -10  -3   5  -1   5  -3   6   7]
 [  2  -2   3   4  -8  -1   5  -6   9  -3]]
wei_hid_out:
 [[ -2  -8   6   9   6]
 [ -9   9   7   1  -6]
 [  2   3   0   3  -9]
 [  8   4 -10  -4  -8]
 [ -8  -4   6   9  -6]
 [ -7   5  -2  -3   4]
 [  3  -7   6  -8  -3]]

active input indices:  [0, 1, 2, 3, 5, 6, 7]
active hidden indices:  [0, 1, 3]

weight_input_hidden after deactivating input nodes:
 [[  1   1   6  -3   1   0  -8]
 [ -2  -5 -10   4   1   3   9]
 [  8   6   4   3  -2   8   5]
 [  4   2 -10  -3  -1   5  -3]
 [  2  -2   3   4  -1   5  -6]]

weight_input_hidden after deactivating hidden nodes:
 [[  1   1   6  -3   1   0  -8]
 [ -2  -5 -10   4   1   3   9]
 [  4   2 -10  -3  -1   5  -3]]

weight_output_hidden after deactivating hidden nodes:
 [[-2 -8  9]
 [-9  9  1]
 [ 2  3  3]
 [ 8  4 -4]
 [-8 -4  9]
 [-7  5 -3]
 [ 3 -7 -8]]


In [17]:
import numpy as np
import random
from scipy.special import expit as activation_function
from scipy.stats import truncnorm
def truncated_normal(mean=0, sd=1, low=0, upp=10):
    return truncnorm(
        (low - mean) / sd, (upp - mean) / sd, loc=mean, scale=sd)
class NeuralNetwork:
    
    def __init__(self, 
                 no_of_in_nodes, 
                 no_of_out_nodes, 
                 no_of_hidden_nodes,
                 learning_rate,
                 bias=None
                ):  
        self.no_of_in_nodes = no_of_in_nodes
        self.no_of_out_nodes = no_of_out_nodes       
        self.no_of_hidden_nodes = no_of_hidden_nodes          
        self.learning_rate = learning_rate 
        self.bias = bias
        self.create_weight_matrices()
        
    def create_weight_matrices(self):
        X = truncated_normal(mean=2, sd=1, low=-0.5, upp=0.5)
        
        bias_node = 1 if self.bias else 0
        n = (self.no_of_in_nodes + bias_node) * self.no_of_hidden_nodes
        X = truncated_normal(mean=2, sd=1, low=-0.5, upp=0.5)
        self.wei_inp_hid = X.rvs(n).reshape((self.no_of_hidden_nodes, 
                                                   self.no_of_in_nodes + bias_node))
        n = (self.no_of_hidden_nodes + bias_node) * self.no_of_out_nodes
        X = truncated_normal(mean=2, sd=1, low=-0.5, upp=0.5)
        self.wei_hid_out = X.rvs(n).reshape((self.no_of_out_nodes, 
                                                    (self.no_of_hidden_nodes + bias_node)))
    def dropout_weight_matrices(self,
                                active_input_percentage=0.70,
                                active_hidden_percentage=0.70):
        # restore wei_inp_hid array, if it had been used for dropout
        self.wei_inp_hid_orig = self.wei_inp_hid.copy()
        self.no_of_in_nodes_orig = self.no_of_in_nodes
        self.no_of_hidden_nodes_orig = self.no_of_hidden_nodes
        self.wei_hid_out_orig = self.wei_hid_out.copy()
        
        active_input_nodes = int(self.no_of_in_nodes * active_input_percentage)
        active_input_indices = sorted(random.sample(range(0, self.no_of_in_nodes), 
                                      active_input_nodes))
        active_hidden_nodes = int(self.no_of_hidden_nodes * active_hidden_percentage)
        active_hidden_indices = sorted(random.sample(range(0, self.no_of_hidden_nodes), 
                                       active_hidden_nodes))
        
        self.wei_inp_hid = self.wei_inp_hid[:, active_input_indices][active_hidden_indices]       
        self.wei_hid_out = self.wei_hid_out[:, active_hidden_indices]
        
        self.no_of_hidden_nodes = active_hidden_nodes
        self.no_of_in_nodes = active_input_nodes
        return active_input_indices, active_hidden_indices
    
    def weight_matrices_reset(self, 
                              active_input_indices, 
                              active_hidden_indices):
        
        """
        self.wei_inp_hid and self.wei_hid_out contain the newly adapted values from the active nodes.
        We have to reconstruct the original weight matrices by assigning the new values 
        from the active nodes
        """
 
        temp = self.wei_inp_hid_orig.copy()[:,active_input_indices]
        temp[active_hidden_indices] = self.wei_inp_hid
        self.wei_inp_hid_orig[:, active_input_indices] = temp
        self.wei_inp_hid = self.wei_inp_hid_orig.copy()
        self.wei_hid_out_orig[:, active_hidden_indices] = self.wei_hid_out
        self.wei_hid_out = self.wei_hid_out_orig.copy()
        self.no_of_in_nodes = self.no_of_in_nodes_orig
        self.no_of_hidden_nodes = self.no_of_hidden_nodes_orig
 
           
    
    def train_single(self, input_vector, target_vector):
        """ 
        input_vector and target_vector can be tuple, list or ndarray
        """
 
        if self.bias:
            # adding bias node to the end of the input_vector
            input_vector = np.concatenate( (input_vector, [self.bias]) )
        input_vector = np.array(input_vector, ndmin=2).T
        target_vector = np.array(target_vector, ndmin=2).T
        output_vector1 = np.dot(self.wei_inp_hid, input_vector)
        output_vector_hidden = activation_function(output_vector1)
        
        if self.bias:
            output_vector_hidden = np.concatenate( (output_vector_hidden, [[self.bias]]) )
        
        output_vector2 = np.dot(self.wei_hid_out, output_vector_hidden)
        output_vector_network = activation_function(output_vector2)
        
        output_errors = target_vector - output_vector_network
        # update the weights:
        tmp = output_errors * output_vector_network * (1.0 - output_vector_network)     
        tmp = self.learning_rate  * np.dot(tmp, output_vector_hidden.T)
        self.wei_hid_out += tmp
        # calculate hidden errors:
        hidden_errors = np.dot(self.wei_hid_out.T, output_errors)
        # update the weights:
        tmp = hidden_errors * output_vector_hidden * (1.0 - output_vector_hidden)
        if self.bias:
            x = np.dot(tmp, input_vector.T)[:-1,:] 
        else:
            x = np.dot(tmp, input_vector.T)
        self.wei_inp_hid += self.learning_rate * x
            
        
    def train(self, data_array, 
              labels_one_hot_array,
              epochs=1,
              active_input_percentage=0.70,
              active_hidden_percentage=0.70,
              no_of_dropout_tests = 10):
        partition_length = int(len(data_array) / no_of_dropout_tests)
        
        for epoch in range(epochs):
            print("epoch: ", epoch)
            for start in range(0, len(data_array), partition_length):
                active_in_indices, active_hidden_indices = \
                           self.dropout_weight_matrices(active_input_percentage,
                                                        active_hidden_percentage)
                for i in range(start, start + partition_length):
                    self.train_single(data_array[i][active_in_indices], 
                                     labels_one_hot_array[i]) 
                    
                self.weight_matrices_reset(active_in_indices, active_hidden_indices)
      
    
    def confusion_matrix(self, data_array, labels):
        cm = {}
        for i in range(len(data_array)):
            res = self.run(data_array[i])
            res_max = res.argmax()
            target = labels[i][0]
            if (target, res_max) in cm:
                cm[(target, res_max)] += 1
            else:
                cm[(target, res_max)] = 1
        return cm
        
    
    def run(self, input_vector):
        # input_vector can be tuple, list or ndarray
        
        if self.bias:
            # adding bias node to the end of the input_vector
            input_vector = np.concatenate( (input_vector, [self.bias]) )
        input_vector = np.array(input_vector, ndmin=2).T
        output_vector = np.dot(self.wei_inp_hid, input_vector)
        output_vector = activation_function(output_vector)
        
        if self.bias:
            output_vector = np.concatenate( (output_vector, [[self.bias]]) )
            
        output_vector = np.dot(self.wei_hid_out, output_vector)
        output_vector = activation_function(output_vector)
    
        return output_vector
    
    
    def evaluate(self, data, labels):
        corrects, wrongs = 0, 0
        for i in range(len(data)):
            res = self.run(data[i])
            res_max = res.argmax()
            if res_max == labels[i]:
                corrects += 1
            else:
                wrongs += 1
        return corrects, wrongs

In [18]:
%matplotlib inline
import matplotlib.pyplot as plt
image_size = 28 # width and length
no_of_different_labels = 10 #  i.e. 0, 1, 2, 3, ..., 9
image_pixels = image_size * image_size
train_data = np.loadtxt("mnist_train.csv", 
                        delimiter=",")
test_data = np.loadtxt("mnist_test.csv", 
                       delimiter=",") 
test_data[:10]

array([[7., 0., 0., ..., 0., 0., 0.],
       [2., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [9., 0., 0., ..., 0., 0., 0.],
       [5., 0., 0., ..., 0., 0., 0.],
       [9., 0., 0., ..., 0., 0., 0.]])

In [19]:
test_data[test_data==255]
test_data.shape

(10000, 785)

In [20]:
fac = 0.99 / 255
train_imgs = np.asfarray(train_data[:, 1:]) * fac + 0.01
test_imgs = np.asfarray(test_data[:, 1:]) * fac + 0.01
train_labels = np.asfarray(train_data[:, :1])
test_labels = np.asfarray(test_data[:, :1])

In [21]:
import numpy as np
lr = np.arange(10)
for label in range(10):
    one_hot = (lr==label).astype(np.int)
    print("label: ", label, " in one-hot representation: ", one_hot)

label:  0  in one-hot representation:  [1 0 0 0 0 0 0 0 0 0]
label:  1  in one-hot representation:  [0 1 0 0 0 0 0 0 0 0]
label:  2  in one-hot representation:  [0 0 1 0 0 0 0 0 0 0]
label:  3  in one-hot representation:  [0 0 0 1 0 0 0 0 0 0]
label:  4  in one-hot representation:  [0 0 0 0 1 0 0 0 0 0]
label:  5  in one-hot representation:  [0 0 0 0 0 1 0 0 0 0]
label:  6  in one-hot representation:  [0 0 0 0 0 0 1 0 0 0]
label:  7  in one-hot representation:  [0 0 0 0 0 0 0 1 0 0]
label:  8  in one-hot representation:  [0 0 0 0 0 0 0 0 1 0]
label:  9  in one-hot representation:  [0 0 0 0 0 0 0 0 0 1]


C:\Users\19144\AppData\Local\Temp\ipykernel_1856\699995814.py:4: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  one_hot = (lr==label).astype(np.int)


In [22]:
lr = np.arange(no_of_different_labels)
# transform labels into one hot representation
train_labels_one_hot = (lr==train_labels).astype(np.float)
test_labels_one_hot = (lr==test_labels).astype(np.float)
# we don't want zeroes and ones in the labels neither:
train_labels_one_hot[train_labels_one_hot==0] = 0.01
train_labels_one_hot[train_labels_one_hot==1] = 0.99
test_labels_one_hot[test_labels_one_hot==0] = 0.01
test_labels_one_hot[test_labels_one_hot==1] = 0.99

C:\Users\19144\AppData\Local\Temp\ipykernel_1856\2912545453.py:3: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  train_labels_one_hot = (lr==train_labels).astype(np.float)
C:\Users\19144\AppData\Local\Temp\ipykernel_1856\2912545453.py:4: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  test_labels_one_hot = (lr==test_labels).astype(np.float)


In [23]:
image_size = 28 # width and length
no_of_different_labels = 10 #  i.e. 0, 1, 2, 3, ..., 9
image_pixels = image_size * image_size

In [24]:
parts = 10
partition_length = int(len(train_imgs) / parts)
print(partition_length)
start = 0
for start in range(0, len(train_imgs), partition_length):
    print(start, start + partition_length)

6000
0 6000
6000 12000
12000 18000
18000 24000
24000 30000
30000 36000
36000 42000
42000 48000
48000 54000
54000 60000


In [25]:
epochs = 3
simple_network = NeuralNetwork(no_of_in_nodes = image_pixels, 
                               no_of_out_nodes = 10, 
                               no_of_hidden_nodes = 100,
                               learning_rate = 0.1)
    
    
 
simple_network.train(train_imgs, 
                     train_labels_one_hot, 
                     active_input_percentage=1,
                     active_hidden_percentage=1,
                     no_of_dropout_tests = 100,
                     epochs=epochs)

epoch:  0
epoch:  1
epoch:  2


In [26]:
corrects, wrongs = simple_network.evaluate(train_imgs, train_labels)
print("accruracy train: ", corrects / ( corrects + wrongs))
corrects, wrongs = simple_network.evaluate(test_imgs, test_labels)
print("accruracy: test", corrects / ( corrects + wrongs))

accruracy train:  0.9068833333333334
accruracy: test 0.9119
